graduateProject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from app01.views import accounts, admin_product, admin_user, recommend, advertisement

urlpatterns = [
    # path('admin/', admin.site.urls),
    # 登录/登出/注册/首页
    path('pre/register/', accounts.pre_register),
    path('register/', accounts.register),
    path('login/', accounts.login),
    path('index/', accounts.index),
    path('logout/', accounts.logout),

    # 产品管理
    path('admin/product/list/', admin_product.product_list),
    path('admin/product/add/', admin_product.product_add),
    path('admin/product/<int:nid>/edit/', admin_product.product_edit),
    path('admin/product/<int:nid>/del/', admin_product.product_del),

    # 用户管理
    path('admin/user/list/', admin_user.user_list),
    path('admin/user/add/', admin_user.user_add),
    path('admin/user/<int:nid>/edit/', admin_user.user_edit),
    path('admin/user/<int:nid>/del/', admin_user.user_del),

    # 产品推荐部分
    path('recom/transition/', recommend.recom_transition),
    path('recom/pre/recommend/', recommend.pre_recom),
    path('recom/recommend/', recommend.recom_show),
    path('recom/pre/ranking_choice/', recommend.pre_ranking_choice),
    path('recom/ranking_choice/', recommend.ranking_choice_show),
    # 排行
    path('recom/<int:nid>/ranking/', recommend.rank),  # 要带typeid来才能判断显示谁的榜单
    # 推荐结果
    path('recom/recommend/result/', recommend.recom_res),

    # 广告
    path('ad/add/', advertisement.ad_add)
]
# 通常，这个URL模式只在开发环境中使用，因此在条件语句中添加一个if settings.DEBUG的判断：

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
# 代码的作用是将MEDIA_URL下的媒体文件映射到MEDIA_ROOT目录中的实际文件。
# 确保将以上代码放置在URL配置文件的最后，以确保它们在其他URL模式之后被匹配。

app01/models.py
from django.db import models


# Create your models here.
class Admin(models.Model):
    '''管理员表'''
    admin_name = models.CharField(verbose_name='管理员名称', max_length=10, null=False)
    password = models.CharField(verbose_name='管理员密码', max_length=100, null=False)


class User(models.Model):
    '''用户表'''
    name = models.CharField(verbose_name='名字', max_length=32, null=False)
    password = models.CharField(verbose_name='密码', max_length=100, null=False)
    age = models.IntegerField(verbose_name='年龄', null=True)
    occupation = models.CharField(verbose_name='职业', max_length=10, null=True)
    gender_choice = (
        (1, '男'),
        (2, '女')
    )
    gender = models.SmallIntegerField(verbose_name='性别', choices=gender_choice, null=False)
    admin = models.ForeignKey(verbose_name='管理员编号', to=Admin, to_field='id', on_delete=models.SET_NULL, null=True,
                              default=1)
    type_choice = (
        (1035, '跑鞋'),
        (9914, '徒步鞋'),
        (1034, '足球鞋'),
        (1032, '篮球鞋'),
        (5853, '羽毛球鞋'),
        (10106, '轮滑鞋'),
        (10304, '综合训练鞋'),
        (1033, '舞蹈鞋'),
        (7429, '高尔夫球鞋'),
        (9906, '运动凉鞋')
    )
    last_choice = models.SmallIntegerField(verbose_name='上一次的选择', choices=type_choice, null=True, default=1035)


class ShoeProduct(models.Model):
    '''鞋类产品表'''
    type_choice = (
        (1035, '跑鞋'),
        (9914, '徒步鞋'),
        (1034, '足球鞋'),
        (1032, '篮球鞋'),
        (5853, '羽毛球鞋'),
        (10106, '轮滑鞋'),
        (10304, '综合训练鞋'),
        (1033, '舞蹈鞋'),
        (7429, '高尔夫球鞋'),
        (9906, '运动凉鞋')
    )
    type = models.SmallIntegerField(verbose_name='鞋产品种类', choices=type_choice)
    picture1 = models.ImageField(verbose_name='图片1', upload_to='images/')
    details1 = models.TextField(verbose_name='产品类型描述1', null=False, default='暂无')
    picture2 = models.ImageField(verbose_name='图片2', upload_to='images/')
    details2 = models.TextField(verbose_name='产品类型描述2', null=False, default='暂无')
    picture3 = models.ImageField(verbose_name='图片3', upload_to='images/')
    details3 = models.TextField(verbose_name='产品类型描述3', null=False, default='暂无')
    rank_link = models.CharField(verbose_name='榜单链接', max_length=64)
    admin = models.ForeignKey(verbose_name='管理员id', to=Admin, to_field='id', null=True, on_delete=models.DO_NOTHING)


class RecomKey(models.Model):
    '''推荐关键字表'''
    # 推荐关键字应给定关键字，不能随意设置
    key1_choice = (
        # 该关键字聚焦于种类
        (1035, '跑鞋'),
        (9914, '徒步鞋'),
        (1032, '篮球鞋'),
        (1034, '足球鞋'),
        (5853, '羽毛球鞋'),
        (10106, '轮滑鞋'),
        (10304, '综合训练鞋'),
        (1033, '舞蹈鞋'),
        (7429, '高尔夫球鞋'),
        (9906, '运动凉鞋')
    )
    key2_choice = {
        # 该关键字聚焦风格
        (1, '时尚'),
        (2, '经典'),
        (3, '复古'),
        (4, '简约'),
        (5, '奇异')
    }
    key3_choice = {
        (1, '高级'),
        (2, '平价'),
        (3, '低价')
    }
    key1 = models.SmallIntegerField(verbose_name='类型', choices=key1_choice, null=True)
    key2 = models.SmallIntegerField(verbose_name='风格', choices=key2_choice, null=True)
    key3 = models.SmallIntegerField(verbose_name='价位', choices=key3_choice, null=True)
    band = models.CharField(verbose_name='品牌', max_length=10, null=True)
    # 用户用关键字进行搜索，所以是用户自己的关键字
    user = models.ForeignKey(verbose_name='用户编号', to=User, to_field='id', on_delete=models.CASCADE, unique=True)
    # 鞋类的种类和key1对应
    shoe_product = models.ForeignKey(verbose_name='鞋类产品id', to=ShoeProduct, to_field='id',
                                     on_delete=models.SET_NULL, null=True)


class Advertisement(models.Model):
    owner = models.CharField(verbose_name='广告商', max_length=30)
    ad_picture = models.ImageField(verbose_name='广告图片', upload_to='images/')
    admin = models.ForeignKey(verbose_name='管理员id', to=Admin, to_field='id', on_delete=models.CASCADE, null=True)

app01/views/accounts.py
from django.http import HttpResponse, JsonResponse
from django.shortcuts import render, redirect

from app01 import models
from app01.utils import forms


# 用户注册前一步
def pre_register(request):
    dict_url = {
        'url': 'register/'
    }
    return JsonResponse(dict_url)


# 用户注册
def register(request):
    if request.method == 'GET':
        form = forms.UserSignupForm()
        print('fuck')
        return render(request, 'register.html', {'form': form})
    else:
        form = forms.UserSignupForm(request.POST)
        if form.is_valid():
            # 表单验证通过，执行保存等操作
            form.save()
            return redirect('/login/')  # 重定向到成功页面
    # 表单验证不通过
    return render(request, 'register.html', {'form': form})


# 用户/管理员登录
def login(request):
    if request.method == 'GET':
        form = forms.LoginForm()
        return render(request, 'login.html', {'form': form})
    else:
        form = forms.LoginForm(data=request.POST)
        if form.is_valid():
            # 管理员登录
            if form.cleaned_data.get('username')[0:6] == 'admin_':
                admin_obj = models.Admin.objects.filter(admin_name=form.cleaned_data.get('username'),
                                                        password=form.cleaned_data.get('password')).first()
                # 登录失败
                if not admin_obj:
                    form.add_error('password', '用户名或密码错误')
                    # 用户名或者密码错误，返回
                    return render(request, 'login.html', {'form': form})
                else:
                    # 登录成功，设置session
                    request.session['info'] = {'id': admin_obj.id, 'name': admin_obj.admin_name}
                    request.session.set_expiry(60 * 60 * 24 * 1)  # 有效期一天                                       
                    return redirect('/index/')
            else:
                # 用户登录
                user_obj = models.User.objects.filter(name=form.cleaned_data.get('username'),
                                                      password=form.cleaned_data.get('password')).first()
                if not user_obj:
                    form.add_error('password', '用户名或密码错误')
                    return render(request, 'login.html', {'form': form})
                else:
                    request.session['info'] = {'id': user_obj.id, 'name': user_obj.name}
                    request.session.set_expiry(60 * 60 * 24 * 1)  # 有效期一天
                    return redirect('/index/')


# 广告加载
def index_ad():
    ad_obj = models.Advertisement.objects.latest('id')
    return ad_obj


# 首页
def index(request):
    # 只处理用户的首页显示
    if request.session['info']['name'][0:6] != 'admin_':
        user_id = request.session['info']['id']
        user_obj = models.User.objects.filter(id=user_id).first()
        # 查询上一次用户的搜索类型
        index_key = user_obj.last_choice
        product_obj = models.ShoeProduct.objects.filter(type=index_key).first()
        # 广告查询
        ad_obj = index_ad()
        # product_dict = {
        #     'picture1': models.ShoeProduct.objects.filter(type=index_key).first().picture1,
        #     'picture2': models.ShoeProduct.objects.filter(type=index_key).first().picture2,
        #     'picture3': models.ShoeProduct.objects.filter(type=index_key).first().picture3,
        #     'description1': models.ShoeProduct.objects.filter(type=index_key).first().details1,
        #     'description2': models.ShoeProduct.objects.filter(type=index_key).first().details2,
        #     'description3': models.ShoeProduct.objects.filter(type=index_key).first().details3,
        # }
        return render(request, 'index.html', {'product_obj': product_obj, 'ad_obj': ad_obj})
    else:  # 管理员进入
        product_obj = models.ShoeProduct.objects.filter(type=1035).first()
        # 广告查询
        ad_obj = index_ad()
        # product_dict = {
        #     'picture1': models.ShoeProduct.objects.filter(type=1035).first().picture1,
        #     'picture2': models.ShoeProduct.objects.filter(type=1035).first().picture2,
        #     'picture3': models.ShoeProduct.objects.filter(type=1035).first().picture3,
        #     # 管理员怎么进入都是跑鞋
        #     'description': models.ShoeProduct.objects.filter(type=1035).first().details1,
        #     'description2': models.ShoeProduct.objects.filter(type=1035).first().details2,
        #     'description3': models.ShoeProduct.objects.filter(type=1035).first().details3,
        # }
        return render(request, 'index.html', {'product_obj': product_obj, 'ad_obj': ad_obj})


# 登出
def logout(request):
    request.session.clear()
    return redirect('/login/')

app01/views/admin_product.py
from django.shortcuts import render, redirect

from app01 import models
from app01.utils import forms


# for admin only
def product_list(request):
    # 管理员有权限访问
    if request.session['info']['name'][0:6] == 'admin_':
        query_set = models.ShoeProduct.objects.all()
        return render(request, 'product_list.html', {'query_set': query_set})
    # 用户无权访问
    return render(request, 'no_right.html')


def product_add(request):
    title = '添加产品类'
    if request == 'GET':
        form = forms.ProductForm()
        return render(request, 'add.html', {'form': form, 'title': title})
    form = forms.ProductForm(request.POST, request.FILES)
    if form.is_valid():
        form.save()
        return redirect('/admin/product/list')
    else:
        return render(request, 'add.html', {'form': form, 'title': title})


def product_edit(request, nid):
    title = '编辑产品类'
    if request.method == 'GET':
        product_obj = models.ShoeProduct.objects.filter(id=nid).first()
        form = forms.ProductForm(instance=product_obj)
        return render(request, 'change.html', {'title': title, 'form': form})
    else:
        form = forms.ProductForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect('/admin/product/list/')
        return render(request, 'change.html', {'title': title, 'form': form})


def product_del(request, nid):
    product_exist = models.ShoeProduct.objects.filter(id=nid).exists()
    if product_exist:
        models.ShoeProduct.objects.filter(id=nid).delete()
        return redirect('/admin/product/list/')

app01/views/admin_user.py
from django.shortcuts import render, redirect

from app01 import models
from app01.utils import forms


# for admin only
def user_list(request):
    # 管理员有权限访问
    if request.session['info']['name'][0:6] == 'admin_':
        query_set = models.User.objects.all()
        return render(request, 'user_list.html', {'query_set': query_set})
    return render(request, 'no_right.html')


def user_add(request):
    title = '增加用户'
    if request.method == 'GET':
        form = forms.UserForm()
        return render(request, 'add.html', {'title': title, 'form': form})
    else:
        form = forms.UserForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('/admin/user/list/')
        return render(request, 'add.html', {'title': title, 'form': form})


def user_edit(request, nid):
    title = '用户编辑'
    if request.method == 'GET':
        user_obj = models.User.objects.filter(id=nid).first()
        form = forms.UserForm(instance=user_obj)
        return render(request, 'change.html', {'title': title, 'form': form})
    else:
        user_obj = models.User.objects.filter(id=nid).first()
        form = forms.UserForm(data=request.POST, instance=user_obj)
        if form.is_valid():
            form.save()
            return redirect('/admin/user/list/')
        return render(request, 'change.html', {'title': title, 'form': form})


def user_del(request, nid):
    models.User.objects.filter(id=nid).first().delete()
    return redirect('/admin/user/list/')

app01/views/advertisement.py
from django.shortcuts import render, redirect

from app01 import models
from app01.utils import forms


def ad_add(request):
    if request.method == 'GET':
        form = forms.AdvertisementForm()
        return render(request, 'add.html', {'form': form})
    else:
        form = forms.AdvertisementForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            # 重定向到首页
            return redirect('/index/')
        return render(request, 'add.html', {'form': form})

app01/views/test.py
import requests
import urllib3
from lxml import etree


def go():
    keyword = '复古篮球运动鞋'
    url = 'https://search.jd.com/Search?keyword=' + keyword + '&suggest=1.his.0.0&wq=' + keyword + '&page=3'
    head = {
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36'
    }
    # 暂时忽略警告
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)
    response = requests.get(url=url, headers=head, verify=False).text
    tree = etree.HTML(response)
    print(response)
    li_list = tree.xpath("//ul[@class='gl-warp clearfix']/li")
    link_list = []  # 商品链接
    commodity_list = []  # 商品名
    price_list = []  # 商品价格
    for li in li_list:
        # 写入商品链接
        link_list.append('https:' + li.xpath(".//div[@class='p-img']/a/@href")[0])
        # 写入商品名
        if (li.xpath(".//div[@class='p-name p-name-type-2']//em/text()[3]")):
            commodity_list.append(li.xpath(".//div[@class='p-name p-name-type-2']//em/text()[1]")[0] +
                                  li.xpath(".//div[@class='p-name p-name-type-2']//em/font[1]/text()")[0] +
                                  li.xpath(".//div[@class='p-name p-name-type-2']//em/text()[2]")[0] +
                                  keyword +
                                  li.xpath(".//div[@class='p-name p-name-type-2']//em/text()[3]")[0]
                                  )
        else:
            commodity_list.append(li.xpath(".//div[@class='p-name p-name-type-2']//em/text()[1]")[0] +
                                  li.xpath(".//div[@class='p-name p-name-type-2']//em/font[1]/text()")[0] +
                                  li.xpath(".//div[@class='p-name p-name-type-2']//em/text()[2]")[0] +
                                  keyword
                                  )
            # 写入商品价格
        price_list.append(li.xpath(".//div[@class='p-price']//i/text()")[0])

        print(link_list)
        print('\n')
        print(commodity_list)
        print('\n')
        print(price_list)


if __name__ == '__main__':
    go()

app01/templates/Layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    {% block css %}{% endblock %}
    <link rel="stylesheet" href="{% static '/plugins/bootstrap-3.4.1-dist/css/bootstrap.css' %}">
</head>
<body>
{#导航栏区域#}
<nav class="navbar navbar-default">
    <div class="container">
        {#导航栏名称#}
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="/index/">运动鞋推荐系统</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            {#导航栏左侧#}
            <ul class="nav navbar-nav">
                <li><a href="/index/">首页</a></li>
                <li><a href="/recom/transition/">商品推荐</a></li>
                <li><a href="/admin/product/list/">产品管理</a></li>    <!--for admin only-->
                <li><a href="/admin/user/list/">用户管理</a></li>
            </ul>
            {#导航栏右侧#}
            <ul class="nav navbar-nav navbar-right">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">{{ request.session.info.name }}<span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li id="ad"><a href="/ad/add/">发布广告</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="/logout/">注销</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.导航栏结束 -->
    </div><!-- /.container-fluid -->
</nav>
<div>
    {% block content %}{% endblock %}
</div>
<script type="text/javascript" src="{% static '/js/jQuery v3.6.3.js' %}"></script>
<script type="text/javascript" src="{% static '/plugins/bootstrap-3.4.1-dist/js/bootstrap.js' %}"></script>
{% block js %}{% endblock %}
<script TYPE="text/javascript">
    // 对用户隐藏广告发布入口
    $(function () {
        hide_ad_event()
    })

    function hide_ad_event() {
        var name = "{{ request.session.info.name }}"
        if (name.substring(0, 6) !== "admin_")
            $("#ad").hide()
    }
</script>
</body>
</html>

app01/templates/add.html
{% extends 'Layout.html' %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                <form  method="post" novalidate enctype="multipart/form-data">   <!--关闭浏览器校验-->
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <!--label就是models中的verbosename-->
                            {{ field.label }}:{{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>   <!--error是一个列表，所以要取首个-->
                        </div>
                    {% endfor %}
                    <input type="submit" class="btn btn-primary" value="提交">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app01/templates/change.html
{% extends 'Layout.html' %}
{% block title %}
    {{ title }}
{% endblock %}
{% block content %}
    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3 class="panel-title">{{ title }}</h3>
            </div>
            <div class="panel-body">
                <form  method="post" novalidate>   <!--关闭浏览器校验-->
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-group">
                            <!--label就是models中的verbosename-->
                            {{ field.label }}:{{ field }}
                            <span style="color: red">{{ field.errors.0 }}</span>   <!--error是一个列表，所以要取首个-->
                        </div>
                    {% endfor %}
                    <input type="submit" class="btn btn-primary" value="提交">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

app01/templates/index.html
{% extends 'Layout.html' %}
{% block content %}
    <div class="container">
        <div class="bs-example" data-example-id="thumbnails-with-custom-content">
            <!--猜你喜欢部分-->
            <div class="row">
                <div><p class="text-primary">猜您喜欢</p></div>
                <div id="guess1" class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img data-src="holder.js/100%x200" alt="100%x200"
                             src="{{ product_obj.picture1.url }}"
                             data-holder-rendered="true" style="height: 200px; width: 100%; display: block;">
                        <div class="caption">
                            <h3>{{ product_obj.get_type_display }}</h3>
                            <p>{{ product_obj.details1 }}</p>
                            <p>
                                <button id="dislike_btn1" class="btn btn-danger">不喜欢</button>
                            </p>
                        </div>
                    </div>
                </div>
                <div id="guess2" class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img data-src="holder.js/100%x200" alt="100%x200"
                             src="{{ product_obj.picture2.url }}"
                             data-holder-rendered="true" style="height: 200px; width: 100%; display: block;">
                        <div class="caption">
                            <h3>{{ product_obj.get_type_display }}</h3>
                            <p>{{ product_obj.details2 }}</p>
                            <p>
                                <button id="dislike_btn2" class="btn btn-danger">不喜欢</button>
                            </p>
                        </div>
                    </div>
                </div>
                <div id="guess3" class="col-sm-6 col-md-4">
                    <div class="thumbnail">
                        <img data-src="holder.js/100%x200" alt="100%x200"
                             src="{{ product_obj.picture3.url }}"
                             data-holder-rendered="true" style="height: 200px; width: 100%; display: block;">
                        <div class="caption">
                            <h3>{{ product_obj.get_type_display }}</h3>
                            <p>{{ product_obj.details3 }}</p>
                            <p>
                                <button id="dislike_btn3" class="btn btn-danger">不喜欢</button>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
            <!--广告部分-->
            <div class="row" style="height: 20%">
                <div class="col-xs-12">
                    <div id="advertisement">
                        <img src="{{ ad_obj.ad_picture.url }}" alt="" style="height: 160px; width: 100%">
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block js %}
    <script type="text/javascript">
        $(function () {
            bind_dislike_btn1_event();
            bind_dislike_btn2_event();
            bind_dislike_btn3_event()
        })

        //点击不喜欢隐藏窗格
        function bind_dislike_btn1_event() {
            $("#dislike_btn1").click(function () {
                $("#guess1").hide()
            })
        }

        function bind_dislike_btn2_event() {
            $("#dislike_btn2").click(function () {
                $("#guess2").hide()
            })
        }

        function bind_dislike_btn3_event() {
            $("#dislike_btn3").click(function () {
                $("#guess3").hide()
            })
        }
    </script>
{% endblock %}

app01/templates/product_list.html
{% extends 'Layout.html' %}
{% block content %}
    {#主体部分#}
    <div class="container">
        {# 新增按钮 #}
        <div style="margin-bottom: 10px">
            <a class="btn btn-primary" href="/admin/product/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新增
            </a>
        </div>
        {# 面板部分 #}
        <div>
            {# 表格头 #}
            <div class="panel-heading">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                鞋类产品列表
            </div>
            {# 表格主体 #}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>类型</th>
                    <th>图片1</th>
                    <th>图片2</th>
                    <th>图片3</th>
                    <th>说明</th>
                    <th>排行</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in query_set %}
                    <tr>
                        <th scope="row">{{ obj.id }}</th>
                        <td>{{ obj.get_type_display }}</td>
                        <td>{{ obj.picture1 }}</td>
                        <td>{{ obj.picture2 }}</td>
                        <td>{{ obj.picture3 }}</td>
                        <td>{{ obj.details }}</td><!--模板语法不能用python的格式化，要用|的方式传到date函数中格式化-->
                        <td>{{ obj.rank_link }}</td><!--模板语法中不允许使用括号，如果有括号jango会自动补齐-->
                        <td>
                            <a class="btn btn-primary btn-xs" href="/admin/product/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/admin/product/{{ obj.id }}/del/">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}

app01/templates/ranking_choice.html
{% extends 'Layout.html' %}
{% block content %}
    <!--第一个循环是行循环-->
    {% for query_set in query_set_list %}
        <div class="row">
            <!--第二个循环是行内元素循环-->
            {% for obj in query_set %}
                <div class="col-xs-6 col-md-3">
                    <a href="/recom/{{ obj.type }}/ranking/" class="thumbnail">
                        <img data-src="holder.js/100%x180" alt="100%x180"
                             style="height: 180px; width: 100%; display: block;"
                             src="{{ obj.picture2.url }}"
                             data-holder-rendered="true">
                        <div class="caption">
                            <h4>{{ obj.get_type_display }}</h4>
                        </div>
                    </a>
                </div>
            {% endfor %}
        </div>
    {% endfor %}
{% endblock %}

app01/templates/user_list.html
{% extends 'Layout.html' %}
{% block content %}
    {#主体部分#}
    <div class="container">
        {# 新增按钮 #}
        <div style="margin-bottom: 10px">
            <a class="btn btn-primary" href="/admin/user/add/">
                <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                新增
            </a>
        </div>
        {# 面板部分 #}
        <div>
            {# 表格头 #}
            <div class="panel-heading">
                <span class="glyphicon glyphicon-list" aria-hidden="true"></span>
                用户列表
            </div>
            {# 表格主体 #}
            <table class="table table-striped">
                <thead>
                <tr>
                    <th>ID</th>
                    <th>姓名</th>
                    <th>密码</th>
                    <th>年龄</th>
                    <th>职业</th>
                    <th>性别</th>
                    <th>上次查询</th>
                    <th>操作</th>
                </tr>
                </thead>
                <tbody>
                {% for obj in query_set %}
                    <tr>
                        <th scope="row">{{ obj.id }}</th>
                        <td>{{ obj.name }}</td>
                        <td>{{ obj.password }}</td>
                        <td>{{ obj.age }}</td>
                        <td>{{ obj.occupation }}</td>
                        <td>{{ obj.get_gender_display }}</td><!--模板语法中不允许使用括号，如果有括号jango会自动补齐-->
                        <td>{{ obj.last_choice }}</td>
                        <td>
                            <a class="btn btn-primary btn-xs" href="/admin/user/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/admin/user/{{ obj.id }}/del/">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}